# Simulation parameters
nusim:
  x0: 0.0       # Initial x of the robot(m)
  y0: 0.0        # Initial y of the robot(m)
  theta0: 0.0   # Initial theta of the robot (rad)
  # Cylinder specs
  obstacles:
    obs_x: [-0.6, 0.6, 0.6]  #x position of the cylinders (m)
    obs_y: [-0.8, -0.8, 0.8] #y position of the cylinders (m)
    radius: 0.038            #radius of the cylinders (m)
  arena:
    x_length: 5    # x-length of the arena(m)
    y_length: 4    # y-length of the arena(m)
  dist:
    vel_mean: 0
    vel_variance: 0.01
    slip_min: .9
    slip_max: 1.1
  sensor:
    basic_sensor_variance: 0.01
    max_range: 1.2
